apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unified-app-prs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prxmat/gitops-repo.git
    targetRevision: main
    path: gitops/charts/unified-app
    helm:
      valueFiles:
        - values.yaml
        - pr-environments/pr-{{ .Values.prNumber }}-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: unified-app-pr-{{ .Values.prNumber }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true