apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unified-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prxmat/gitops-repo.git
    targetRevision: HEAD
    path: gitops/charts/unified-app
    helm:
      values: |
        global:
          environment: development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 